# Generated by Django 2.2 on 2020-08-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GGJC_question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=225)),
                ('q_count', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=225)),
                ('where', models.CharField(max_length=128)),
                ('page', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='JTGC_question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=225)),
                ('q_count', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=225)),
                ('where', models.CharField(max_length=128)),
                ('page', models.CharField(max_length=128)),
            ],
        ),
    ]
