# Generated by Django 2.2 on 2020-08-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['type'], 'verbose_name_plural': '说明文档'},
        ),
        migrations.AlterModelOptions(
            name='ggjc_question',
            options={'ordering': ['id'], 'verbose_name_plural': '公共基础知识题库'},
        ),
        migrations.AlterModelOptions(
            name='jtgc_question',
            options={'ordering': ['id'], 'verbose_name_plural': '交通工程题库'},
        ),
        migrations.AlterField(
            model_name='ggjc_question',
            name='page',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ggjc_question',
            name='q_count',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ggjc_question',
            name='where',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='jtgc_question',
            name='page',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='jtgc_question',
            name='q_count',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jtgc_question',
            name='where',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
