# Generated by Django 2.2 on 2020-09-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200827_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ggjc_question',
            name='page',
            field=models.CharField(blank='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ggjc_question',
            name='where',
            field=models.CharField(blank='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='jtgc_question',
            name='page',
            field=models.CharField(blank='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='jtgc_question',
            name='where',
            field=models.CharField(blank='', max_length=128, null=True),
        ),
    ]
