# Generated by Django 2.2 on 2020-09-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200901_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_end_line',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=225, verbose_name='考试名称')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='考试日期')),
                ('exam_location', models.CharField(blank=True, max_length=20, null=True, verbose_name='考试地点')),
                ('exam_class', models.CharField(blank=True, max_length=20, null=True, verbose_name='考试科目')),
            ],
            options={
                'verbose_name_plural': '考试科目及时间设定',
                'ordering': ['id'],
            },
        ),
    ]
