# Generated by Django 2.2 on 2020-09-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_exam_end_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ggjc_question',
            name='answer',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='ggjc_question',
            name='page',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ggjc_question',
            name='where',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='jtgc_question',
            name='page',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='jtgc_question',
            name='q_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jtgc_question',
            name='where',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
