# Generated by Django 2.2 on 2020-09-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='合同名称')),
                ('no', models.CharField(max_length=200, unique=True, verbose_name='合同编号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合同金额')),
                ('signing_date', models.DateField(null=True, verbose_name='签订日期')),
                ('p_name', models.CharField(max_length=200, verbose_name='对应机场名称')),
                ('p_no', models.IntegerField(verbose_name='对应机场编号')),
                ('person_name', models.CharField(default='-', max_length=200, null=True, verbose_name='联系人姓名')),
                ('person_phone', models.CharField(default='-', max_length=20, null=True, verbose_name='联系人电话')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=20, null=True, verbose_name='联系人性别')),
                ('person_title', models.CharField(max_length=100, null=True, verbose_name='联系人职位信息')),
                ('first_party', models.CharField(max_length=200, null=True, verbose_name='甲方单位')),
                ('notes', models.TextField(max_length=200, null=True, verbose_name='备注信息')),
                ('c_time', models.DateField(auto_now_add=True, null=True, verbose_name='登记时间')),
            ],
            options={
                'verbose_name_plural': 'ZHZ合同详情',
                'ordering': ['signing_date'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=200, verbose_name='设备')),
                ('d_type', models.CharField(max_length=200, null=True, verbose_name='设备型号')),
                ('quantity', models.CharField(max_length=18, null=True, verbose_name='设备数量')),
                ('append', models.CharField(max_length=255, null=True, verbose_name='设备附件')),
                ('usefor', models.TextField(max_length=200, null=True, verbose_name='测量目的')),
                ('standard', models.TextField(max_length=200, null=True, verbose_name='适应标准')),
                ('manual', models.TextField(max_length=4000, null=True, verbose_name='设备说明')),
                ('ups_time', models.DateField(null=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name_plural': '中航质设备',
                'ordering': ['d_name', 'd_type'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('p_no', models.IntegerField(verbose_name='项目编号')),
                ('name', models.CharField(max_length=200, verbose_name='联系人姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=20, verbose_name='性别')),
                ('title', models.CharField(max_length=100, verbose_name='职位信息')),
                ('area', models.CharField(max_length=200, verbose_name='籍贯或活动省市')),
                ('company', models.CharField(max_length=200, verbose_name='公司名称')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='邮箱')),
                ('idNO', models.CharField(max_length=18, null=True, unique=True, verbose_name='身份证号')),
                ('up_name', models.CharField(max_length=20, null=True, verbose_name='登记人')),
                ('ups_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name_plural': '行业联系人',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200, unique=True, verbose_name='机场名称')),
                ('p_no', models.IntegerField(unique=True, verbose_name='机场编号')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('provence', models.CharField(max_length=200, verbose_name='所在省份')),
                ('region', models.CharField(choices=[('华北', '华北'), ('华东', '华东'), ('东北', '东北'), ('华南', '华南'), ('西北', '西北'), ('新疆', '新疆')], max_length=100, verbose_name='所属管理区')),
                ('use_cate', models.CharField(choices=[('民用', '民用'), ('军用', '军用'), ('军民合用', '军民合用')], max_length=20, verbose_name='使用性质')),
                ('construction_situation', models.CharField(choices=[('既有', '既有'), ('新增', '新增'), ('研究布局', '研究布局'), ('在建', '在建')], max_length=12, verbose_name='建设情况')),
                ('run_length', models.CharField(max_length=200, verbose_name='跑道长度')),
                ('run_class', models.CharField(max_length=200, verbose_name='跑道等级')),
                ('terminal_area', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='航站楼面积')),
                ('active_time', models.DateField(verbose_name='启用时间')),
                ('throughput', models.CharField(max_length=255, verbose_name='吞吐量')),
                ('aircraft_sorties', models.CharField(max_length=255, verbose_name='架次/日')),
            ],
            options={
                'verbose_name_plural': '全国机场项目详情',
                'ordering': ['p_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200, verbose_name='机场名称')),
                ('sys_name', models.CharField(choices=[('航显', '航显'), ('布线', '布线'), ('安防', '安防'), ('广播', '广播')], max_length=30, verbose_name='系统名称')),
                ('d_name', models.CharField(max_length=200, verbose_name='设备名')),
                ('d_type', models.CharField(max_length=200, null=True, verbose_name='设备型号')),
                ('d_quantity', models.CharField(max_length=18, null=True, verbose_name='设备数量')),
                ('madeCountryClass', models.CharField(choices=[('中国', '中国'), ('外国', '外国'), ('未知', '未知')], max_length=8, null=True, verbose_name='made by')),
                ('madeCountry', models.CharField(max_length=18, null=True, verbose_name='制造国家名')),
                ('set_date', models.DateField(auto_now_add=True, null=True, verbose_name='大概安装年月')),
                ('alarmDate', models.DateField(auto_now_add=True, null=True, verbose_name='提醒年月')),
                ('alarmLeft', models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='安装后计时年')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name_plural': '各机场设备统计',
                'ordering': ['p_name', 'sys_name', '-c_time'],
            },
        ),
        migrations.CreateModel(
            name='TradeContracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200, unique=True, verbose_name='机场项目名称')),
                ('company_name', models.CharField(max_length=200, unique=True, verbose_name='公司名称')),
                ('contract_name', models.CharField(max_length=200, unique=True, verbose_name='合同名称')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='合同金额')),
                ('contract_content', models.TextField(max_length=800, null=True, verbose_name='合同范围内容')),
                ('person_name', models.CharField(max_length=200, null=True, verbose_name='合同负责人名字')),
                ('tenderr', models.CharField(max_length=200, unique=True, verbose_name='招标人')),
                ('contract_date', models.DateField(null=True, verbose_name='签订日期')),
                ('location', models.CharField(max_length=200, null=True, verbose_name='公司地址')),
                ('chairman', models.CharField(max_length=200, null=True, verbose_name='法人/董事长/老大')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name_plural': '各机场施工单位信息',
                'ordering': ['p_name', 'contract_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=20, verbose_name='性别')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name_plural': '用户名',
                'ordering': ['-c_time'],
            },
        ),
    ]
