# Generated by Django 2.2 on 2020-09-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='area',
            field=models.CharField(max_length=200, null=True, verbose_name='籍贯或活动省市'),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.CharField(max_length=200, null=True, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='联系人姓名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_name',
            field=models.CharField(max_length=200, null=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_no',
            field=models.IntegerField(null=True, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=20, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='职位信息'),
        ),
    ]
