# Generated by Django 2.2 on 2020-09-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0003_auto_20200901_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradecontracts',
            name='c_time',
            field=models.DateField(verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='tradecontracts',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='tradecontracts',
            name='contract_name',
            field=models.CharField(max_length=200, verbose_name='合同名称'),
        ),
        migrations.AlterField(
            model_name='tradecontracts',
            name='tenderr',
            field=models.CharField(max_length=200, verbose_name='招标人'),
        ),
    ]
