# Generated by Django 2.2 on 2020-09-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0005_auto_20200901_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradecontracts',
            name='contract_name',
            field=models.CharField(max_length=200, null=True, verbose_name='合同名称'),
        ),
    ]
