# Generated by Django 2.2 on 2020-09-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0006_auto_20200908_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='contract_content',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='合同范围内容'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='person_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='联系人姓名'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='person_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人电话'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='person_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人职位信息'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=20, null=True, verbose_name='联系人性别'),
        ),
        migrations.AlterField(
            model_name='device',
            name='manual',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='设备说明'),
        ),
        migrations.AlterField(
            model_name='device',
            name='standard',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='适应标准'),
        ),
        migrations.AlterField(
            model_name='device',
            name='usefor',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='测量目的'),
        ),
        migrations.AlterField(
            model_name='projectdevice',
            name='alarmLeft',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='安装后计时年'),
        ),
        migrations.AlterField(
            model_name='projectdevice',
            name='d_quantity',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='设备数量'),
        ),
        migrations.AlterField(
            model_name='projectdevice',
            name='d_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='设备型号'),
        ),
        migrations.AlterField(
            model_name='projectdevice',
            name='madeCountry',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='制造国家名'),
        ),
        migrations.AlterField(
            model_name='projectdevice',
            name='madeCountryClass',
            field=models.CharField(blank=True, choices=[('中国', '中国'), ('外国', '外国'), ('未知', '未知')], max_length=8, null=True, verbose_name='made by'),
        ),
        migrations.AlterField(
            model_name='tradecontracts',
            name='chairman',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='法人/董事长/老大'),
        ),
        migrations.AlterField(
            model_name='tradecontracts',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同金额'),
        ),
        migrations.AlterField(
            model_name='tradecontracts',
            name='contract_content',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='合同范围内容'),
        ),
        migrations.AlterField(
            model_name='tradecontracts',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='签订日期'),
        ),
        migrations.AlterField(
            model_name='tradecontracts',
            name='contract_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='合同名称'),
        ),
        migrations.AlterField(
            model_name='tradecontracts',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='公司地址'),
        ),
        migrations.AlterField(
            model_name='tradecontracts',
            name='person_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='合同负责人名字'),
        ),
        migrations.AlterField(
            model_name='tradecontracts',
            name='tenderr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='招标人'),
        ),
    ]
