# Generated by Django 2.2 on 2020-09-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0009_auto_20200911_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuggageCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True, verbose_name='公司名称')),
                ('legal_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='法人')),
                ('registered_money', models.CharField(blank=True, max_length=200, null=True, verbose_name='注册资本')),
                ('establishDate', models.DateField(blank=True, null=True, verbose_name='成立日期')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司地址')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='联系电话')),
                ('key_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='主要人员')),
                ('social_credit_code', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='统一社会信用代码')),
                ('taxName', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='纳税人名称')),
                ('taxID', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='纳税人识别号')),
                ('taxType', models.CharField(blank=True, choices=[('小规模纳税人', '一般纳税人')], max_length=60, null=True, unique=True, verbose_name='纳税人类型')),
                ('patents_name', models.CharField(max_length=200, verbose_name='专利名称')),
                ('certificates', models.CharField(max_length=200, verbose_name='资质证书')),
                ('business_scope', models.TextField(blank=True, max_length=2500, null=True, verbose_name='经营范围')),
                ('product_intro', models.TextField(blank=True, max_length=2500, null=True, verbose_name='产品介绍')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name_plural': '行李设备厂家',
                'ordering': ['-c_time', 'company_name'],
            },
        ),
        migrations.AlterField(
            model_name='projectdevice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
