# Generated by Django 2.2 on 2020-09-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0011_auto_20200914_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='籍贯或活动省市'),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='person',
            name='idNO',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=20, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='职位信息'),
        ),
        migrations.AlterField(
            model_name='person',
            name='up_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='登记人'),
        ),
    ]
