# Generated by Django 2.2 on 2020-09-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0012_auto_20200915_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendWebsit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('websit_name', models.CharField(max_length=150, unique=True, verbose_name='网站名称')),
                ('websit_link', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='网址')),
                ('webType', models.CharField(blank=True, choices=[('公司用', '公司用')], max_length=60, null=True, unique=True, verbose_name='纳税人类型')),
                ('webDoc', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='介绍')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name_plural': '友情链接',
                'ordering': ['-c_time', 'websit_name'],
            },
        ),
    ]
