# Generated by Django 2.2 on 2020-09-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0013_friendwebsit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendwebsit',
            name='webDoc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='friendwebsit',
            name='webType',
            field=models.CharField(blank=True, choices=[('公司用', '公司用'), ('自己用', '自己用'), ('娱乐用', '娱乐用')], max_length=60, null=True, verbose_name='网站性质'),
        ),
    ]
