# Generated by Django 2.2 on 2020-11-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0014_auto_20200924_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing_end_line',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thing_name', models.CharField(max_length=225, verbose_name='事件名称')),
                ('thing_date', models.DateField(blank=True, null=True, verbose_name='截至发生日期')),
                ('thing_location', models.CharField(blank=True, max_length=20, null=True, verbose_name='事件地点')),
                ('thing_class', models.CharField(blank=True, max_length=20, null=True, verbose_name='事件分类')),
            ],
            options={
                'verbose_name_plural': '事件及时间设定',
                'ordering': ['thing_date'],
            },
        ),
    ]
