# Generated by Django 2.2 on 2021-01-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0016_auto_20201202_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='aready_get_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='总收款金额'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='project_status',
            field=models.CharField(blank=True, choices=[('是', '是'), ('否', '否')], max_length=10, null=True, verbose_name='项目是否关闭'),
        ),
    ]
