# Generated by Django 2.2 on 2021-01-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0018_auto_20210111_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='project_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='项目当前状态'),
        ),
    ]
