# Generated by Django 2.2 on 2021-01-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0019_auto_20210111_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='合同名称'),
        ),
    ]
