# Generated by Django 2.2 on 2021-02-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0020_auto_20210111_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='邮寄地址'),
        ),
    ]
