# Generated by Django 2.2 on 2021-03-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0021_person_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCompanyProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NewProjectID', models.CharField(max_length=200, unique=True, verbose_name='新立项项目编号')),
                ('NewProject_name', models.CharField(max_length=150, unique=True, verbose_name='新立项项目名称')),
                ('NewProject_type', models.CharField(blank=True, choices=[('检测类', '检测类'), ('外包类', '外包类'), ('配合类', '配合类')], max_length=60, null=True, verbose_name='项目性质')),
                ('NewProject_status', models.CharField(blank=True, choices=[('进行中', '进行中'), ('已签约', '已签约'), ('已作废', '已作废'), ('已配合完毕', '已配合完毕')], max_length=60, null=True, verbose_name='项目状态')),
                ('NewProjectDoc', models.TextField(blank=True, max_length=2000, null=True, verbose_name='此项目背景介绍')),
                ('p_name', models.CharField(max_length=200, null=True, verbose_name='机场项目名称')),
                ('p_no', models.IntegerField(null=True, verbose_name='机场项目编号')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='项目创建时间')),
            ],
            options={
                'verbose_name_plural': '新立项项目',
                'ordering': ['-c_time', 'NewProject_name'],
            },
        ),
    ]
