# Generated by Django 2.2 on 2021-03-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0022_newcompanyproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='NP_Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NewProjectID', models.CharField(max_length=200, unique=True, verbose_name='新立项项目编号')),
                ('note_one', models.TextField(blank=True, max_length=5000, null=True, verbose_name='事项记录')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='项目创建时间')),
            ],
            options={
                'verbose_name_plural': 'NP事情记录',
                'ordering': ['-c_time', 'NewProjectID'],
            },
        ),
        migrations.AddField(
            model_name='newcompanyproject',
            name='Contracts_no',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='签约的合同编号'),
        ),
    ]
