# Generated by Django 2.2 on 2021-03-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0023_auto_20210313_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='np_note',
            name='NewProjectID',
            field=models.CharField(max_length=200, verbose_name='新立项项目编号'),
        ),
    ]
