# Generated by Django 2.2 on 2021-03-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0024_auto_20210313_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='NewProjectID',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='新立项项目编号'),
        ),
    ]
