# Generated by Django 2.2 on 2021-03-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0025_person_newprojectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcompanyproject',
            name='Contracts_no',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='签约的合同编号'),
        ),
    ]
