# Generated by Django 2.2 on 2021-03-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0026_auto_20210315_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcompanyproject',
            name='p_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='机场项目名称'),
        ),
        migrations.AlterField(
            model_name='newcompanyproject',
            name='p_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='机场项目编号'),
        ),
    ]
