# Generated by Django 2.2 on 2021-03-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0028_auto_20210316_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='np_note',
            name='NewProject_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='新立项项目名称'),
        ),
        migrations.AlterField(
            model_name='newcompanyproject',
            name='NewProject_type',
            field=models.CharField(blank=True, choices=[('检测类', '检测类'), ('外包类', '外包类'), ('配合类', '配合类'), ('其他类', '其他类')], max_length=60, null=True, verbose_name='项目性质'),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='region',
            field=models.CharField(choices=[('华北', '华北'), ('华东', '华东'), ('东北', '东北'), ('华南', '华南'), ('西北', '西北'), ('西南', '西南'), ('新疆', '新疆')], max_length=100, verbose_name='所属管理区'),
        ),
    ]
