# Generated by Django 2.2 on 2021-04-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0029_auto_20210318_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='booktest', verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '图片内容',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='np_note',
            options={'ordering': ['-c_time', 'NewProjectID'], 'verbose_name_plural': '新立项项目NP事情记录'},
        ),
    ]
