# Generated by Django 2.2 on 2021-04-03 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZHZ_DATABASH', '0030_auto_20210402_1928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='img',
        ),
    ]
